apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proyecto-ingress
  namespace: proyecto-tesis
spec:
  rules:
  - host: proyecto.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proyecto-php
            port:
              number: 80
